### ISSUE TITLE
Consider posting to Forum

### ISSUE THREAD

**Issue by andfanilo** [liunux4odoo/streamlit-raw-echarts#1]
Hey @liunux4odoo !

I stumbled on this by pure luck. Nice!
Did you consider posting this on https://discuss.streamlit.io/ ? I couldn't find a post from you there.

Have a nice day,
Fanilo

**Comment by liunux4odoo** [comment]
Hi Fanilo,


Thanks for your advice, I would post a brief introduction to streamlit's forum in several days.


Best regards,
liunux


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liunux4odoo/streamlit-raw-echarts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[liunux4odoo/streamlit-raw-echarts] Consider posting to Forum (Issue #1)





 
Hey @liunux4odoo !
 
I stumbled on this by pure luck. Nice!
 Did you consider posting this on https://discuss.streamlit.io/ ? I couldn't find a post from you there.
 
Have a nice day,
 Fanilo
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andfanilo** [comment]
Nice :)  saw your post! 

https://discuss.streamlit.io/t/new-component-raw-echarts-config-echarts-option-with-full-api-support/22851
